[Terrarium - Providers]: Implementation of Upload Feature - 1
terrariumcloud/terrarium pull request #75
Opened 2024-06-17 07:16 UTC by anjanikshree12

### This PR includes:
* upload feature support being implemented as a part of CIEDEV-3780
* Protobuff definitions for upload service having functionalities such as upload provider binary, shasum and signature files for the storage and gateway.
* gRPC code generated by protoc compiler tool from the protobuff definitions.

> [!IMPORTANT]  
>In the upcoming PRs as a part of same feature support, the missing methods will be added.(current build failing) and this PR will be the base PR to remaining ones.

2024-06-17 09:20 UTC, odelanno approved these changes

2024-06-18 10:00 UTC, adcharre requested changes
Can you add stubs for the missing methods so that the build is at least successful even though they do nothing.

2024-06-21 11:12 UTC, vmilovanovicc submitted a review, later dismissed

2024-06-21 16:43 UTC, adcharre approved these changes

2024-06-21 16:54 UTC, merged